services:
  database:
    container_name: database
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=wolfgang
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PW}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ~/wolfgang-data/:/data/db
  front:
    container_name: front
    build:
      context: .
      dockerfile: packages/front/src/docker/DockerFile.front
    ports:
      - 80:80
    depends_on:
      - back-main
      - back-game
  back-main:
    container_name: back-main
    build:
      context: .
      dockerfile: packages/back-main/src/docker/DockerFile.back-main
    ports:
      - ${MAIN_PORT}:${MAIN_PORT}
    depends_on:
      - back-registery
      - database
  back-game:
    container_name: back-game
    build:
      context: .
      dockerfile: packages/back-game/src/docker/DockerFile.back-game
    ports:
      - ${GAME_PORT}:${GAME_PORT}
    depends_on:
      - back-registery
      - database
  back-registery:
    container_name: back-registery
    build:
      context: .
      dockerfile: packages/back-registery/src/docker/DockerFile.back-registery
    ports:
      - ${REGISTERY_PORT}:${REGISTERY_PORT}
