export enum VarEnvEnum {
    MAIN_URL = 'MAIN_URL',
    MAIN_PORT = 'MAIN_PORT',
    GAME_URL = 'GAME_URL',
    GAME_PORT = 'GAME_PORT',
    REGISTERY_URL = 'REGISTERY_URL',
    REGISTERY_PORT = 'REGISTERY_PORT',
    DB_URL = 'DB_URL',
    DB_PORT = 'DB_PORT',
    DB_USER = 'DB_USER',
    DB_PW = 'DB_PW',
    JWT_COOKIE_NAME = 'JWT_COOKIE_NAME',
    JWT_ISSUER = 'JWT_ISSUER',
    JWT_AUDIENCE = 'JWT_AUDIENCE',
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRES = 'JWT_EXPIRES'
}