name: Create branch when card is moved in ongoing story list

on:
  repository_dispatch:
    types:
      - card-moved-in-ongoing-story-list

jobs:
  create:
    name: Create branch
    runs-on: ubuntu-latest
    steps:
      - name: Unifying new-branch name
        id: find_and_replace
        run: |
          string="${{ github.event.client_payload.card_title }}"
          string=$(echo $string | tr '[:upper:]' '[:lower:]')
          string=${string// /-}
          string=${string//\'/-}
          echo "result=feature/${string}" >> "$GITHUB_OUTPUT"
          
      - name: Get the repository name and the owner name
        id: find_repository_owner_name
        run: |
          string="${{ github.repository }}"
          IFS='/'
          read -a stringArray <<< "$string"
          echo "owner=${stringArray[0]}" >> "$GITHUB_OUTPUT"
          echo "repo=${stringArray[1]}" >> "$GITHUB_OUTPUT"
      
      - name: Create branch with the unified name
        uses: bodinsamuel/renovate-automatic-branch@v1
        with:
          github-token: ${{ secrets.WRITE_TOKEN }}
          repo-owner: ${{ steps.find_repository_owner_name.outputs.owner }}
          repo-name: ${{ steps.find_repository_owner_name.outputs.repo }}
          branch-to-create: ${{ steps.find_and_replace.outputs.result }}
          branch-base: develop
