name: Create branch when card is moved in ongoing story list

on:
  repository_dispatch:
    types:
      - card-moved-in-ongoing-story-list

env:
  GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN }}

jobs:
  create:
    runs-on: ubuntu-latest
    
    steps:
      - name: Unifying new-branch name
        id: find_and_replace
        run: |
          string="${{github.event.client_payload.card_title}}"
          string=$(echo $string | tr '[:upper:]' '[:lower:]')
          string=${string// /-}
          string=${string//\'/-}
          echo "result=feature/${string}" >> $GITHUB_OUTPUT
    
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: '${{ steps.find_and_replace.outputs.result }}'
          sha: '${{ github.event.pull_request.head.sha }}'
