name: Create branch when card is moved in ongoing story list

on:
  repository_dispatch:
    types:
      - card-moved-in-ongoing-story-list

jobs:
  create:
    name: Create branch
    runs-on: ubuntu-latest
    steps:
      - name: Unifying new-branch name
        id: find_and_replace
        run: |
          string="${{github.event.client_payload.card_title}}"
          string=$(echo $string | tr '[:upper:]' '[:lower:]')
          string=${string// /-}
          string=${string//\'/-}
          echo "result=feature/${string}" >> $GITHUB_OUTPUT
    
      - name: Create branch with the unified name
        uses: monoku/sync-branches-pr@0.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN }}
          SOURCE_BRANCH: 'develop'
          TARGET_BRANCH_STARTS_WITH: ${{ steps.find_and_replace.outputs.result }}
