name: Create branch when card is moved in ongoing story list

on:
  repository_dispatch:
    types:
      - card-moved-in-ongoing-story-list

jobs:
  create:
    name: Create branch
    runs-on: ubuntu-latest
    steps:
      - name: Unifying new-branch name
        id: find_and_replace
        run: |
          string="${{github.event.client_payload.card_title}}"
          string=$(echo $string | tr '[:upper:]' '[:lower:]')
          string=${string// /-}
          string=${string//\'/-}
          echo "result=feature/${string}" >> $GITHUB_OUTPUT
    
      - name: Create branch with the unified name
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
        with:
          repository_owner: czyrok
          repository_name: wolfgang
          new_branch_name: ${{ steps.find_and_replace.outputs.result }}
          new_branch_ref: main
          access_token: ${{ secrets.WRITE_TOKEN }}
